const data = [
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "fantasy",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "fantasy",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "Saquon Barkley",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
  {
    img: "/images/laImage.svg",
    heading: "fantasy",
    subHeading: "RB • #26",
    ranking: "Ranking# 01",
    imgHeading: "New York Giants",
    height: "6-0",
    weight: "232",
    experience: "5",
    age: "25",
    current: "Current value",
    price: "0.033 ADA",
  },
];
export { data };
